title: My Blog
description: A simple blog powered by Jekyll
theme: minima

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown

# Permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/